#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# build_cdi_manifest.py
#
# List the weekly CDI grids that actually exist in data/Drough_TS/ and write a
# tiny JS manifest the interactive map reads. This is what lets newly added
# grids show up in the map's date picker / animation automatically after the
# next build -- with no code edit. The browser cannot list a directory itself,
# so the build does it here and commits the result alongside the new data.
#
#   Input  : data/Drough_TS/CDI_YYYYMMDD.txt      (one grid per week)
#   Output : assets/interactive/cdi-manifest.js   (window.IDM_CDI_DATES = [...])
#
# Run standalone:   python3 build_cdi_manifest.py
# Also invoked by build.py as the 'cdimanifest' stage on every build.
#
# If this manifest is ever absent, the map's buildDateList() falls back to a
# generated weekly sequence up to today, so the date list still self-extends.
# -----------------------------------------------------------------------------
import argparse
import re
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent
PAT = re.compile(r"^CDI_(\d{4})(\d{2})(\d{2})\.txt$")


def collect_dates(src_dir):
    """Return a sorted (ascending) list of date objects parsed from CDI_*.txt names."""
    dates = set()
    if not src_dir.is_dir():
        return []
    for p in src_dir.iterdir():
        m = PAT.match(p.name)
        if not m:
            continue
        try:
            dates.add(date(int(m.group(1)), int(m.group(2)), int(m.group(3))))
        except ValueError:
            # skip impossible dates (e.g. CDI_20260230.txt)
            continue
    return sorted(dates)


def write_manifest(repo, dates):
    out = repo / "assets" / "interactive" / "cdi-manifest.js"
    iso = [d.isoformat() for d in dates]
    arr = ", ".join('"%s"' % s for s in iso)
    header = (
        "/* AUTO-GENERATED by build_cdi_manifest.py - do not edit by hand.\n"
        " * Weekly CDI grids present in data/Drough_TS/ (CDI_YYYYMMDD.txt), as ISO\n"
        " * dates, oldest first. The interactive map reads this so newly added grids\n"
        " * appear in the date picker / animation after the next build (no code edit).\n"
        " * If this file is missing, the map falls back to a generated weekly sequence\n"
        " * up to today. Regenerate with: python3 build_cdi_manifest.py\n"
        " */\n"
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header + "window.IDM_CDI_DATES = [" + arr + "];\n", encoding="utf-8")
    return out, iso


def main():
    ap = argparse.ArgumentParser(
        description="Write assets/interactive/cdi-manifest.js from data/Drough_TS/."
    )
    ap.add_argument("--repo", default=str(REPO), help="repo root (default: this script's dir)")
    args = ap.parse_args()

    repo = Path(args.repo).resolve()
    src_dir = repo / "data" / "Drough_TS"
    dates = collect_dates(src_dir)
    out, iso = write_manifest(repo, dates)

    rel = out.relative_to(repo) if out.is_relative_to(repo) else out
    if iso:
        print("cdi-manifest: %d weeks (%s -> %s) -> %s" % (len(iso), iso[0], iso[-1], rel))
    else:
        print("cdi-manifest: no CDI_YYYYMMDD.txt found under %s (wrote empty manifest -> %s)"
              % (src_dir, rel))
    return 0


if __name__ == "__main__":
    sys.exit(main())
